# Example config for kleinCommand

# Settings for kleinCommand
[settings]
server_name = "klein server"

# Variable overrides
[variables]
string1="example"
int1=1

# Custom commands
[custom_commands]
# Generate commands with kleinCommand or configure here
[[custom_commands.games]]
name = "example"
status_command="docker ps --format '{{.Names}}'"
start_command="echo start"
stop_command="echo stop"